#pragma once

#define PROJECTENGINE_BUILD_UNKNOWN			"unknown"
#define PROJECTENGINE_BUILD_DEBUG			"debug"
#define PROJECTENGINE_BUILD_RELEASE			"release"

#if defined(PEDEBUG)
    #define BUILD_TYPE	PROJECTENGINE_BUILD_DEBUG
    #define PROJECTENGINE_DEBUG
#elif defined(PERELEASE)
    #define BUILD_TYPE	PROJECTENGINE_BUILD_RELEASE
    #define PROJECTENGINE_RELEASE
#else
    #define BUILD_TYPE	PROJECTENGINE_BUILD_UNKNOWN
    #define PROJECTENGINE_UNKNOWN
#endif